#!/usr/bin/env bash

if [[ "$OSTYPE" != "darwin"* ]]; then
    printf "This is for macOS only"
    exit 1
fi

if xcode-select -p 2>&1 &>/dev/null; then
    printf "%s\n" $(xcode-select -p)
    printf "Command line tools are installed properly.\n"
else
    printf "Please install command line tools and rerun the script."
    xcode-select --install
fi
