#!/usr/bin/env bash

if [[ "$OSTYPE" != "darwin"* ]]; then
    printf "This is for macOS only"
    exit 1
fi

if xcode-select -p 2>&1; then
    printf "%s\n" $(xcode-select -p)
else
    printf "Not installed?"
fi
